/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/indexOLDbackup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/map-view` | `/map-view`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/report-details` | `/report-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/my-reports` | `/my-reports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/report-submission` | `/report-submission`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/indexOLDbackup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/map-view` | `/map-view`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/report-details` | `/report-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/my-reports` | `/my-reports`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/report-submission` | `/report-submission`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/indexOLDbackup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/map-view${`?${string}` | `#${string}` | ''}` | `/map-view${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/report-details${`?${string}` | `#${string}` | ''}` | `/report-details${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(user)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/my-reports${`?${string}` | `#${string}` | ''}` | `/my-reports${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/report-submission${`?${string}` | `#${string}` | ''}` | `/report-submission${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/indexOLDbackup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/map-view` | `/map-view`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/report-details` | `/report-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/my-reports` | `/my-reports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/report-submission` | `/report-submission`; params?: Router.UnknownInputParams; };
    }
  }
}
